### ISSUE TITLE
Application not launch detected root device

### ISSUE THREAD

**Issue by lopin123** [LEAGUE-OF-NINE/AppPealing#1]
Please help me...I've been attached the logs file.
[modules_2024-07-02T14_31_44.660635.log](https://github.com/user-attachments/files/16064263/modules_2024-07-02T14_31_44.660635.log)

**Comment by pufferffish** [comment]
Seems like you've enabled AppPealing for an app that doesn't have Inka AppSealing? 

Please make sure AppPealing is only enabled for the app you want to target.

**Comment by pufferffish** [comment]
Does the [new release](https://github.com/LEAGUE-OF-NINE/AppPealing/releases/tag/1.1) fix this issue?

**Comment by pufferffish** [comment]
> I'am sure that apps used Inks AppSealing. because I'am edit the findandHookMethod for showAlertDialog parameter and its success. can I send you apk from discord or telegram?

Sure. My discord tag is @zenocara.

**Comment by lopin123** [comment]
I've been send
