### ISSUE TITLE
there was a problem parsing the package on bluestacks 5

### ISSUE THREAD

**Issue by Ahmed-Mahmod-Salem** [LEAGUE-OF-NINE/AppPealing#2]
when I try to install the module in Bluestacks 5, Pie_64x, I get the error, "there was a problem parsing the package"

**Comment by Ahmed-Mahmod-Salem** [comment]
nevermind, I recompiled the code with the correct API level and it worked. thanks much

**Comment by pufferffish** [comment]
What API level did you use?

**Comment by Ahmed-Mahmod-Salem** [comment]
`android {
    namespace 'com.october.apppealing'
    compileSdk 34

    defaultConfig {
        applicationId "com.october.apppealing"
        minSdk 28
        targetSdk 34
        versionCode 1
        versionName "1.2"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        externalNativeBuild {
            cmake {
                cppFlags ''
            }
        }
    }
`
this is the part I changed in build.gradle, the minsdk is the most important parameter, also here is the compiled APK https://drive.google.com/file/d/1TxnG8sHK4brjmFnEFnWe6HlScAWAugtY/view

**Comment by pufferffish** [comment]
Fixed in release 1.3
