### ISSUE TITLE
accessibility detection 

### ISSUE THREAD

**Issue by Vinay8423** [LEAGUE-OF-NINE/AppPealing#3]
Appsealing still detect accessibility on, like if I use  auto clicker and give accessibility permission  to auto clicker then appsealing detect permission on please remove this 🙏🙏

**Comment by pufferffish** [comment]
Which app? Screenshots?

**Comment by Vinay8423** [comment]
![IMG_20240723_084252](https://github.com/user-attachments/assets/79bd3f20-5a2d-43f7-b129-1c53faba29e2)

**Comment by Vinay8423** [comment]
![IMG_20240723_084536](https://github.com/user-attachments/assets/f66cc29b-19dc-45d1-8e56-bfa3a47796f6)
Also detect developer option on.

**Comment by pufferffish** [comment]
These detections don't seem to be done by AppSealing so it's outside the scope of this project. I suggest you look into using AppPealing with other modules that bypass these detections such as [this](https://github.com/Xposed-Modules-Repo/io.github.alexdonh.noaccessibilityservices) and [this](https://play.google.com/store/apps/details?id=net.accelf.devoptshide&hl=en&gl=US).

**Comment by Vinay8423** [comment]
When I using ( no-accessibility-services)
Then my game not open instant crash 😔
